version: '3.0'
services:
  hub:
    # image: robokit-cognitive-hub
    image: wwlib/robokit:robokit-cognitive-hub
    env_file:
      - hub.env
    ports:
      - '8082:8082'
  chitchat:
    # image: robokit-cloud-skill
    image: wwlib/robokit:robokit-cloud-skill
    env_file:
      - chitchat.env
    ports:
      - '8083:8083'
  redislima:
    image: redislabs/redismod
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    # ports:
    #   - '6379:6379'
    volumes:
      - redis_data_lima:/data
  lima:
    # image: lima-service
    image: wwlib/robokit:lima-service
    env_file:
      - lima-service.env
    ports:
      - '8084:8084'
    volumes:
      - ./.limarc.json:/usr/app/.limarc.json

volumes:
  redis_data_lima:
    external: false