version: '3.0'
services:
  redis:
    image: redislabs/redismod
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    # ports:
    #   - '6379:6379'
    volumes:
      - redis_data:/data
  app:
    # image: reasongraph-service
    image: registry.digitalocean.com/wwlib-registry/reasongraph-service
    env_file:
      - compose.env
    ports:
      - '8000:8000'
      - '80:80'
  hub:
    # image: robokit-cognitive-hub
    image: registry.digitalocean.com/wwlib-registry/reasongraph-service:robokit-cognitive-hub
    env_file:
      - hub.env
    ports:
      - '8082:8082'
  chitchat:
    # image: robokit-cloud-skill
    image: registry.digitalocean.com/wwlib-registry/reasongraph-service:robokit-cloud-skill
    env_file:
      - chitchat.env
    ports:
      - '8083:8083'
  lima:
    # image: lima-service
    image: wwlib/robokit:lima-service
    env_file:
      - lima-service.env
    ports:
      - '8084:8084'
volumes:
  redis_data:
    external: false
    